# 配置文件
#   1.thymeleaf配置
#   2. servlet配置
#   3. 当前活跃配置文件（指定后缀即可）： 生产配置 or 开发配置
spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    servlet:
      content-type: text/html
  profiles:
    active: dev
  messages:
    basename: i18n/messages



