#开发环境配置文件：
#          1.数据库配置
#          2.jpa设置
#          3.日志级别，文件位置配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


logging:
  level:
    root: info
    com.star: debug
  file:
    name: log/blog-dev.log